### ISSUE TITLE
can't run command

### ISSUE THREAD

**Issue by meaverick** [tobyxdd/anchorDNS#5]
pi@raspberrypi2:/bin/anchorDNS $ sudo  anchorDNS -d 114.114.114.114 -a 8.8.8.8 -c ChinaCIDR.txt

-bash: anchorDNS: command not found

Linux raspberrypi2 4.1.19-v7+ #853 SMP Wed Mar 9 18:09:16 GMT 2016 armv7l GNU/Linux

Need Java？

**Comment by tobyxdd** [comment]
of course you need Java & you should run this like
./anchorDNS
as it's a bash script
