### ISSUE TITLE
请问如何安装运行？

### ISSUE THREAD

**Issue by meaverick** [tobyxdd/anchorDNS#6]
按照 说明装了 java 但是无法运行anchorDNS
Linux raspberry pi2 4.1.19-v7+ #858 SMP Tue Mar 15 15:56:00 GMT 2016 armv7l GNU/Linux
pi@pi2:/bin $ java -version
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) Client VM (build 25.91-b14, mixed mode)

pi@pi2:/bin $ anchorDNS
-bash: anchorDNS: command not found

我解压anchorDNS到/bin目录下
Thanks

**Comment by tobyxdd** [comment]
./anchorDNS
请先了解Linux基本命令格式。。

**Comment by tobyxdd** [comment]
我仔细看了下 你试试 bash anchorDNS 别忘加x权限。。

**Comment by meaverick** [comment]
Thanks. 晚上回家试试

**Comment by meaverick** [comment]
pi@Pi3:/ $ uname -a
Linux Pi3 4.4.9-v7+ #884 SMP Fri May 6 17:28:59 BST 2016 armv7l GNU/Linux
pi@Pi3:/ $ sudo chmod +x /bin/anchorDNS
pi@Pi3:/ $ bash /bin/anchorDNS
/bin/anchorDNS: /bin/anchorDNS: is a directory
pi@Pi3:/ $ bash anchorDNS
bash: anchorDNS: No such file or directory
